# Generated by Django 5.0.4 on 2024-05-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_project_bathrooms_remove_project_bedrooms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('design', 'Design Phase'), ('construction', 'Under Construction'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned', max_length=20),
        ),
    ]
