# Generated by Django 5.0.4 on 2024-05-05 10:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='project_poster_images/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
    ]
