# Generated by Django 5.0.4 on 2024-05-07 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_experts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Experts',
            new_name='Expert',
        ),
    ]
